### PR TITLE
Chicken Decapitation

### PR DESCRIPTION
**Pull request by comp500**
Science says that chickens do not feel pain, and are not harmed by the gentle removal of their heads. Therefore, this pull request is verified to be 100% humane.

Changes:
- Cleaned up imports for some files
- Removed a useless event handler registration thing
- Added a chicken head
  - Can be worn:
image
  - Obtained by left-clicking a chicken with an axe
  - Can be placed back onto a headless chicken
  - Placeable in four directions for decoration
- JEI support for chicken decapitation:
  JEI support demonstration

### CODE REVIEW

**Comment by vtesterlwg** [comment]
ok

**Comment by comp500** [comment]
🐔

**Comment by vtesterlwg** [comment]
>not merge?????

**Comment by quat1024** [comment]
try again in a few days, not really feeling up to it rn

**Comment by quat1024** [comment]
sorry btw :(

**Comment by comp500** [comment]
👋 merge?

**Comment by quat1024** [comment]
Noooo its been like 3 momths how did i forget ahout it for this long

Ill merge rn and push a build when o get to my pc next

**Pull request merged**
